
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jersey_roothp
      - POSTGRES_USER=jersey_user
      - POSTGRES_PASSWORD=jersey_secure_pass_123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jersey_user -d jersey_roothp"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://jersey_user:jersey_secure_pass_123@db:5432/jersey_roothp
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY:-pk_test_dummy}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_dummy}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_dummy}
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - default

volumes:
  postgres_data: