# Generated by Django 5.0.2 on 2025-06-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_order_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
