# Generated by Django 5.0.2 on 2025-06-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_add_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
