# Generated by Django 5.0.2 on 2025-06-28 20:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from admin (rejection reasons, etc.)'),
        ),
        migrations.AddField(
            model_name='event',
            name='listing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Platform listing fee for this event', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='listing_paid',
            field=models.BooleanField(default=False, help_text='Has the listing fee been paid?'),
        ),
        migrations.AddField(
            model_name='event',
            name='listing_paid_at',
            field=models.DateTimeField(blank=True, help_text='When the listing fee was paid', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='listing_tier',
            field=models.CharField(blank=True, help_text='Pricing tier applied', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the event was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', help_text='Event status in the system', max_length=20),
        ),
    ]
