# Generated by Django 5.0.2 on 2025-06-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_event_admin_notes_event_listing_fee_and_more'),
    ]

    operations = [
    ]
